# Any of the below config properties can be provided via Environment Variables
server:
  port: 8081
  logLevel: debug
  logFormat: text
  timeout: 5000ms
#  host: https://cfproxy.local.pcfdev.io
sm:
  user: admin
  password: admin
  host: https://smanager.local.pcfdev.io
  osbApi: /v1/osb
  requestTimeout: 6000ms
  skipSslValidation: true
cf:
  client:
    apiAddress: http://api.local.pcfdev.io
    username: admin
    password: admin
    skipSslValidation: true
    httpClient:
      timeout: 6000ms
  reg:
    user: admin
    password: admin
